### ISSUE TITLE
Testing 

### ISSUE THREAD

**Issue by djolereject** [Shopify/limiter#25]
I'm not sure this belongs to issues so please move if there is a more appropriate place for questions of this type.

I'm wondering how one could test the method with the rate limit, for example, if we have `limit_method :tick, rate: 300` and we want to ensure that the `tick` method is not called more frequently, how could that test look like? I'm guessing Timecop could be used but I haven't found solution.
I guess most users of the app have this need and explanation might have its place in README if it would be simple.

Thanks!

**Comment by gs-sendoso** [comment]
Hi, @djolereject Did you find a solution? Can you please share your findings here?
