### ISSUE TITLE
wrong gem name in README

### ISSUE THREAD

**Issue by toao** [Shopify/limiter#3]
Hi, the gem name ```limiter``` specified in the README is wrong, the correct one is ```ruby-limiter```. This might cause some confusion, please fix :)

**Comment by mbklein** [comment]
@marlonmantilla Try `gem 'ruby-limiter', require: 'limiter'` in your `Gemfile`

**Comment by sbfaulkner** [comment]
my bad... I'd only used this in a project without bundler... so, missed that mistake

@mbklein 's workaround should work, and I'm pushing a fix shortly
