### ISSUE TITLE
Use `Process.clock_gettime(Process::CLOCK_MONOTONIC)` instead of `Time`?

### ISSUE THREAD

**Issue by srpouyet** [Shopify/limiter#4]
Hi,

Thank you for open sourcing this!

I recently came across a post that I think might be useful for this gem: [Elapsed time with Ruby, the right way](https://blog.dnsimple.com/2018/03/elapsed-time-with-ruby-the-right-way/). The author writes:

> To recap: system clock is constantly floating and it doesn't move only forwards. If your calculation of elapsed time is based on it, you're very likely to run into calculation errors or even outages.

> Remember: wall clock is for telling time, monotonic clock is for measuring time. ⏰

This is why you probably don't want to use `Time` but `Process.clock_gettime(Process::CLOCK_MONOTONIC)` to calculate the elapsed time.

Cheers!

**Comment by sbfaulkner** [comment]
good point - this was accurate enough for our original need, but CLOCK_MONOTONIC would definitely be "more correct"

**Comment by sbfaulkner** [comment]
we'll need to either get support for clock_gettime in Timecop, or mock our own equivalent for testing

**Comment by sbfaulkner** [comment]
https://github.com/travisjeffery/timecop/issues/220

**Comment by srpouyet** [comment]
Thanks @sbfaulkner ! 👍
