### ISSUE TITLE
Redis-backed distributed rate limiter based on this project

### ISSUE THREAD

**Issue by mbklein** [Shopify/limiter#5]
Hi, I just wanted to make y'all aware of [redrate](https://github.com/nulib/redrate), a gem based almost entirely on this one that uses Redis instead of instance variables to store the ring, head, and mutex. This allows multiple running instances of the code to share a queue, even across different servers, making it possible to rate-limit access to a shared external resource.

Thanks @sbfaulkner for the interface, code, and (especially) tests that made the port possible!

**Comment by sbfaulkner** [comment]
glad it was helpful @mbklein

**Comment by f3ndot** [comment]
Would either of you be willing to merge this functionality (Redis-backed) here as an option? @mbklein you've done great work but fear that without it being formally adopted into `limiter` it will become abandonware (with all due respect). @sbfaulkner would you be willing to entertain such functionality?

I'm sure I have time to help contribute this endeavour if all parties are willing.

**Comment by sbfaulkner** [comment]
I don't see this project evolving much beyond its current state - limiter was intentionally as simple as possible, and I explicitly didn't want redis, etc. dependencies

perhaps participating in redrate and promoting its use over this one is the better option?
