### ISSUE TITLE
How to sync rate limit among multiple servers?

### ISSUE THREAD

**Issue by gamesover** [Shopify/limiter#54]
Hello,

Upon reviewing the documentation, I noticed there is no mention of synchronizing rate limits across multiple servers. My question pertains to implementing rate limiting within an application running in a Docker container. Specifically, if I were to deploy 10 such containers, all making calls to the same third-party API, how would I ensure that the rate limit is consistently enforced across all these containers? Is there a recommended approach for managing and communicating rate limits among multiple Docker containers to avoid surpassing the API's rate limit constraints?

Thank you for your advice.

**Comment by sbfaulkner** [comment]
this is not supported, nor planned
